# Generated by Django 4.2.7 on 2025-06-29 20:10

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Admin')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqam')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50, unique=True, verbose_name='Rang nomi')),
                ('kodi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Rang kodi')),
                ('hex_kodi', models.CharField(blank=True, help_text='Masalan: #FF0000', max_length=7, null=True, verbose_name='Hex kodi')),
                ('qo_shilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt")),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Buyurtmachi nomi')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon raqam')),
                ('manzil', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('tavsif', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha ma'lumot")),
                ('qo_shilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt")),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Buyurtmachi',
                'verbose_name_plural': 'Buyurtmachilar',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, unique=True, verbose_name='Material nomi')),
                ('tavsif', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('qo_shilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt")),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Material turi',
                'verbose_name_plural': 'Material turlari',
                'ordering': ['nomi'],
            },
        ),
        migrations.CreateModel(
            name='TikuvMashina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raqami', models.CharField(max_length=20, unique=True, verbose_name='Mashina raqami')),
                ('nomi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mashina nomi')),
                ('holati', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faol emas'), ('repair', "Ta'mirlanmoqda")], default='active', max_length=20, verbose_name='Holati')),
                ('qo_shilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan vaqt")),
            ],
            options={
                'verbose_name': "To'quv mashina",
                'verbose_name_plural': "To'quv mashinalari",
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partiya_raqami', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Partiya raqami')),
                ('material_gramaji_turi', models.CharField(choices=[('sm', 'Santimetr (sm)'), ('gram', 'Gramm (g)')], default='sm', max_length=4, verbose_name='Material gramaji turi')),
                ('material_gramaji', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Material gramaji')),
                ('kilogramm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zakaz (kg)')),
                ('status', models.CharField(choices=[('waiting', 'Kutish'), ('progress', 'Jarayonda'), ('completed', 'Tugatilgan')], default='waiting', max_length=10, verbose_name='Status')),
                ('kiritilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Kutishga qo'yilgan vaqt")),
                ('tugatilgan_vaqt', models.DateTimeField(blank=True, null=True, verbose_name='Tugatildi vaqti')),
                ('buyurtmachi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textil_app.customer', verbose_name='Buyurtmachi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('material_rangi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textil_app.color', verbose_name='Material rangi')),
                ('material_turi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textil_app.materialtype', verbose_name='Material turi')),
                ('tikuv_mashina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textil_app.tikuvmashina', verbose_name='Tikuv mashina')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiallar',
                'ordering': ['-kiritilgan_vaqt'],
            },
        ),
    ]
