# Generated by Django 4.2.7 on 2025-07-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textil_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterial',
            name='izoh',
            field=models.TextField(blank=True, help_text="Qo'shimcha izoh yoki eslatma", null=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='material',
            name='izoh',
            field=models.TextField(blank=True, help_text="Qo'shimcha izoh yoki eslatma", null=True, verbose_name='Izoh'),
        ),
    ]
