# Generated by Django 4.2.7 on 2025-06-29 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('textil_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMaterial',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('partiya_raqami', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Partiya raqami')),
                ('material_gramaji_turi', models.CharField(choices=[('sm', 'Santimetr (sm)'), ('gram', 'Gramm (g)')], default='sm', max_length=4, verbose_name='Material gramaji turi')),
                ('material_gramaji', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Material gramaji')),
                ('kilogramm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Zakaz (kg)')),
                ('status', models.CharField(choices=[('waiting', 'Kutish'), ('progress', 'Jarayonda'), ('completed', 'Tugatilgan')], default='waiting', max_length=10, verbose_name='Status')),
                ('kiritilgan_vaqt', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Kutishga qo'yilgan vaqt")),
                ('tugatilgan_vaqt', models.DateTimeField(blank=True, null=True, verbose_name='Tugatildi vaqti')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('buyurtmachi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='textil_app.customer', verbose_name='Buyurtmachi')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="Qo'shgan foydalanuvchi")),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material_rangi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='textil_app.color', verbose_name='Material rangi')),
                ('material_turi', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='textil_app.materialtype', verbose_name='Material turi')),
                ('tikuv_mashina', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='textil_app.tikuvmashina', verbose_name='Tikuv mashina')),
            ],
            options={
                'verbose_name': 'historical Material',
                'verbose_name_plural': 'historical Materiallar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
